# Generated by Django 5.2.8 on 2026-09-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='therapists/')),
                ('qualification', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=150)),
                ('about', models.TextField()),
                ('specialization', models.TextField()),
                ('languages', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
